### PR TITLE
Added missing language dir and modified 2 *.js files for correct link…

### PR DESCRIPTION
**Pull request by rezeau**
…s to translations.

Signed-off-by: Joseph Rézeau <joseph@rezeau.org>

### CODE REVIEW

**Comment by icc** [comment]
Won't moving the translations from the _checkboxes widget_ to the _drag-question editor_ make the _checkboxes widget_ dependant on the _drag-question editor_? It would be nice if this component was reusable by other editors as well.

**Comment by rezeau** [comment]
@icc I understand your comment. I moved the translations from the checkboxes widget to the drag-question editor because I thought it was the only way for the translated strings in H5PEditor.DynamicCheckboxes.js to read language files inside the language folder! It seems that the h5p-editor-drag-question library is the only one (in H5P) to contain more references to 2 H5PEditor*.js files: H5PEditor.DragQuestion.js and H5PEditor.DynamicCheckboxes.js, hence the translations problem and hence my little workaround.

**Comment by icc** [comment]
Ah, sorry I misunderstood. I thought they were two separate libraries. This should be OK.  I've created an issue for testing and merging your changes: [HFP-486](https://h5ptechnology.atlassian.net/browse/HFP-486)

**Comment by rezeau** [comment]
OK then. By the way, when my PR is merged  IsabelZydun's German language file could be completed and merged too. See #1

**Comment by icc** [comment]
Great! We'll try to get to this as quickly as possible then.

**Comment by icc** [comment]
Looks and work great, thank you!

**Pull request merged**
